name: Build and test Linux, Mac and Windows versions for x86_64, x86, aarch64 and armv7 architectures on Ubuntu, MacOS and Windows each
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          [
            stable-x86_64-unknown-linux-gnu,
            stable-x86_64-apple-darwin,
            stable-x86_64-pc-windows-msvc,
            stable-i686-unknown-linux-gnu,
            stable-i686-pc-windows-msvc,
            stable-aarch64-unknown-linux-gnu,
            stable-aarch64-apple-darwin,
            stable-aarch64-pc-windows-msvc,
            stable-armv7-unknown-linux-gnueabihf,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
  test:
    name: Test
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          [
            stable-x86_64-unknown-linux-gnu,
            stable-x86_64-apple-darwin,
            stable-x86_64-pc-windows-msvc,
            stable-i686-unknown-linux-gnu,
            stable-i686-pc-windows-msvc,
            aarch64-unknown-linux-gnu,
            aarch64-apple-darwin,
            aarch64-pc-windows-msvc,
            armv7-unknown-linux-gnueabihf,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
